cd C:\Users\luis\Documents\sanidad\expDatos 
node getLocalUpdates.js
node getLocalSanitario.js
node getLocalComedor.js
node getLocalCercado.js
node getLocalAOP.js
node getLocalAM.js
node getLocalUP.js
node getLocalAQ.js
node getLocaltools.js
node getLocalAgua.js
node getLocalMaq.js